#!/bin/bash -l

#SBATCH --job-name=DAC	# Name for your job
#SBATCH --comment="DAC"	# Comment for your job

#SBATCH --account=factor		# Project account to run your job under
#SBATCH --partition=tier3		# Partition to run your job on

#SBATCH --output=%x_%j.out		# Output file
#SBATCH --error=%x_%j.err		# Error file

#SBATCH --mail-user=fxcsbi@rit.edu	# Email address to notify
#SBATCH --mail-type=END			# Type of notification emails to send

#SBATCH --time=0-06:00:00		# Time limit
#SBATCH --nodes=1			# How many nodes to run on
#SBATCH --ntasks=2			# How many tasks per node
#SBATCH --cpus-per-task=2		# Number of CPUs per task
#SBATCH --mem-per-cpu=30g		# Memory per CPU

spack env activate factor-x86_64-24062401

perl auto_correlation_multiple_new4_corrected_new.pl chr1_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr1_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr1_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr2_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr2_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr2_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr3_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr3_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr3_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr4_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr4_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr4_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr5_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr5_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr5_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt

perl auto_correlation_multiple_new4_corrected_new.pl chr6_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr6_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr6_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr7_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr7_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr7_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr8_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr8_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr8_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr9_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr9_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr9_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr10_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr10_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr10_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt

perl auto_correlation_multiple_new4_corrected_new.pl chr11_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr11_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr11_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr12_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr12_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr12_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr13_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr13_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr13_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr14_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr14_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr14_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr15_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr15_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr15_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt

perl auto_correlation_multiple_new4_corrected_new.pl chr16_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr16_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr16_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr17_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr17_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr17_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr18_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr18_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr18_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr19_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr19_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr19_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr20_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr20_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr20_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt

perl auto_correlation_multiple_new4_corrected_new.pl chr21_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr21_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr21_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chr22_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr22_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chr22_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt
perl auto_correlation_multiple_new4_corrected_new.pl chrX_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chrX_human_inVitro_sorted_dyad_147bp_type4_new_no_0.txt chrX_human_inVitro_sorted_dyad_147bp_type4_new_no_0_auto_correlation.txt



